version: '3.3'
services:
  api:
    container_name: api
    build: 
      context: ./appli
    ports:
      - 5001:5001
  ui:
      container_name: ui
      build:
        context: ./vue-projet
      volumes:
        - '.:/app'
        - '/app/node_modules'
      ports:
        - '8080:8080'